#!/usr/bin/env Rscript
args<-commandArgs(trailingOnly=TRUE);root<-normalizePath(if(length(args))args[[1]]else".",mustWork=TRUE);source(file.path(root,"full_atlas_primary_integration_v1","00_common.R"))
full_dir<-file.path(root,"pre_integration","full_atlas_primary_v1");transfer_dir<-file.path(full_dir,"annotation_transfer_by_library");run_dir<-file.path(full_dir,"scmerge2_primary_runs")
required<-c(file.path(full_dir,"full_annotation_transfer_summary.tsv"),file.path(full_dir,"full_annotation_transfer_compartment_counts.tsv"),file.path(full_dir,"full_annotation_transfer_confidence_counts.tsv"),file.path(full_dir,"full_primary_scmerge2_plan.tsv"),file.path(full_dir,"full_primary_scmerge2_metrics.tsv"),file.path(run_dir,"T_NK_combined__ruvK5__kPB5__full_v1.rds"),file.path(run_dir,"Monocyte_DC_combined__ruvK2__kPB5__full_v1.rds"));missing<-required[!file.exists(required)];if(length(missing))stop("Missing outputs:\n",paste(missing,collapse="\n"))
files<-list.files(transfer_dir,pattern="\\.tsv\\.gz$",full.names=TRUE);if(length(files)!=158L)stop("Expected 158 transfer files")
n_total<-0L;n_low<-0L;comp_counts<-integer()
for(f in files){z<-read_tsv(f);n_total<-n_total+nrow(z);n_low<-n_low+sum(z$transfer_confidence=="low");tab<-table(z$integration_compartment_primary_v1);for(nm in names(tab)){if(!nm %in% names(comp_counts))comp_counts[nm]<-0L;comp_counts[nm]<-comp_counts[nm]+as.integer(tab[[nm]])}}
if(n_total!=665816L)stop("Expected 665816 cells; found ",n_total)
tnk<-readRDS(file.path(run_dir,"T_NK_combined__ruvK5__kPB5__full_v1.rds"));mono<-readRDS(file.path(run_dir,"Monocyte_DC_combined__ruvK2__kPB5__full_v1.rds"));if(length(tnk$cells)!=comp_counts[["T_NK_combined"]])stop("T/NK count mismatch");if(length(mono$cells)!=comp_counts[["Monocyte_DC_combined"]])stop("Mono/DC count mismatch")
summary<-data.frame(metric=c("n_cells_total","n_libraries","n_low_confidence_transfer","low_confidence_fraction","n_T_NK_integrated","n_Monocyte_DC_integrated","T_NK_ruvK","Monocyte_DC_ruvK","k_pseudoBulk"),value=c(n_total,length(files),n_low,n_low/n_total,length(tnk$cells),length(mono$cells),tnk$ruvK,mono$ruvK,tnk$k_pseudoBulk));write_tsv(summary,file.path(full_dir,"full_primary_integration_verification.tsv"));cat("\n=== FULL PRIMARY INTEGRATION VERIFICATION ===\n");print(summary,row.names=FALSE);cat("\nPASS: full Atlas primary integration outputs are internally consistent\n")
