name: sepsis-scrna-r43
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3
  - r-essentials
  - r-matrix
  - r-seurat
  - r-seuratobject
  - r-dplyr
  - r-tibble
  - r-readr
  - r-stringr
  - r-purrr
  - r-ggplot2
  - r-patchwork
  - r-data.table
  - bioconductor-singlecellexperiment
  - bioconductor-singler
  - bioconductor-scuttle
  - bioconductor-scater
  - bioconductor-dropletutils
  - bioconductor-celldex
  - bioconductor-miqc
  - bioconductor-delayedarray
  - bioconductor-genomicranges
  - bioconductor-summarizedexperiment
  - bioconductor-annotationhub
  - bioconductor-experimenthub
  - bioconductor-annotationdbi
  - bioconductor-biocparallel
  - r-remotes
  - r-devtools
